### ISSUE TITLE
New staging evironment

### ISSUE THREAD

**Issue by jamesjjk** [peddlerlabs/peddler-docs-merchant-api#2]
The new staging environment is available:

For web (UI) based interactions: https://stagingv2.pdlr.it/
For API based interactions (such as CRUD or oAuth requests): https://staging-api.pdlr.it/
API endpoints: https://staging-api.pdlr.it/api

- [x] Images are currently being synchronised in S3
- [x] Merchant account being created for Magento team

**Comment by jamesjjk** [comment]
@OlehPitsyk 
Note that https://stagingv2.pdlr.it/ requires additinally basic auth (hiding our new features from general public):
U: devsrulesupreme 
P: helloearth!

**Comment by jamesjjk** [comment]
- In order to go to the GB staging (UK) site which contains the most content and category structure: https://gb-stagingv2.pdlr.it/

**Comment by OlehPitsyk** [comment]
@jamesjjk thanks a lot!we are looking through it

**Comment by jamesjjk** [comment]
@OlehPitsyk @phongle79 
I'm working on oAuth authentication documentation for the API. So you can try the oauth funnels. I will create specific accounts for you to use and authenticate against.

**Comment by ikatsiuba** [comment]
> * In order to go to the GB staging (UK) site which contains the most content and category structure: https://gb-stagingv2.pdlr.it/

@jamesjjk   what about api for GB staging? https://gb-stagingv2.pdlr.it/api/  ?

**Comment by jamesjjk** [comment]
@ikatsiuba 
- The API endpoint you are requesting does not exist - https://gb-stagingv2.pdlr.it/ IS to switch to a UK/GB Localised version of the staging site, it is not related to API
- The only entrypoint you need for api is: https://staging-api.pdlr.it/api
