### ISSUE TITLE
Post product from Magento

### ISSUE THREAD

**Issue by ikatsiuba** [peddlerlabs/peddler-docs-merchant-api#4]
Could you please create request example of  "Post new product"(/products/postProduct). We are trying to send data but every time receive only err.invalidRequest which is not detail.  
I suppose that  the problem might be related to the field "images", we send just url of image, but on Peddler frontend there is aditional request for uploading images before the product creating.

**Comment by phongle79** [comment]
@ikatsiuba 
The following is an example data for posting the product I copy from unit tests.
```
{ tags: [ { name: 'Car' } ],
  retailcurrency: 'USD',
  retailprice: 100000,
  description: '<p>This is an amazing car</p>',
  images: [ { name: 'https://redis.io/images/redis-white.png' } ],
  brand: { name: 'Mercedes' },
  category: { name: 'Technology'},
  product: { name: 'Super Mercedes 2016' } }
```

**Comment by ikatsiuba** [comment]
@phongle79   thanks! it works fine for me now.
